README.md
Added base rules to the README with point breakdown
=> added rules and point breakdowns

views/player_join_game.html
=> Created View Player_Join_Game

views/player-place-bets.html
Tested in both crome on desktop as well as chrome mobile. Resolves #22
=> Resolves #22 adds player betting view

views/displaywinningbet.html
=> initial html for display winning bet

views/congrat.html
=> initial html for endgame display congrat message

views/displayCorrectAnswer.html
=> initial html for display correct answer

views/player_skip_rules.html
=> Created View Player_Skip_Rules

views/Gameboard_QuestionDisplay.html
=> Issue 11: Displays Question, timer, and number of players answered.

views/gameboard_endround_leaderboard.html
resolves #15 Added leaderboard layout Needs to be made responsive
=> Add points leaderboard

package-lock.json, package.json, src/components/Gameboard/CreateGame.js
Make server and Frontend start at the same time
=> Clean stuff

src/actions/index.js, src/components/Player/JoinRoom.js, src/reducers/gameplay_reducer.js
=> Get questions

src/components/Player/PlaceBets.js
Added a checkbox to the placebets component that can be used for the doubledown. This is just cosmetic it needs logic added to make it functional.
resolves #69
=> Add checkbox for doubledown to PlaceBets component

src/components/Gameboard/AnswerPlaceBets.js, src/components/Gameboard/AnswerSeeBets.js, src/components/Gameboard/AnswersLeaderBoard.js, src/components/Gameboard/Congrats.js, src/components/Gameboard/CorrectAnswer.js, src/components/Gameboard/CreateGame.js, src/components/Gameboard/PointsLeaderBoard.js, src/components/Gameboard/Question.js, src/components/Gameboard/QuestionAsk.js, src/components/Gameboard/QuestionNumber.js, src/components/Gameboard/RoomCode.js, src/components/Gameboard/RoundNumber.js, src/components/Gameboard/Rules.js, src/components/Gameboard/Submitted.js, src/components/Gameboard/Timer.js, src/components/Player/Answer.js, src/components/Player/Blank.js, src/components/Player/ErrorScreen.js, src/components/Player/JoinRoom.js, src/components/Player/PlaceBets.js, src/components/Player/PlayAgain.js, src/components/Player/SkipRules.js
- Tested not to break existing functionality on master. 
- Adds base level dummy functions needed for react and redux to work together.
- Code Cleanup: made indentation inside components consistant
=> Add functions needed to wire up redux to react

server.js, src/actions/index.js, src/actions/socket_actions.js, src/components/Gameboard/QuestionNumber.js, src/components/Gameboard/RoomCode.js, src/components/Player/Blank.js, src/components/Player/StartGame.js, src/components/screens.js, src/reducers/gameplay_reducer.js
Modifies how the screen switching takes place and resolves #44
=> Issue 44 display question number

src/actions/index.js, src/actions/socket_actions.js, src/components/Gameboard/CreateGame.js, src/components/Gameboard/QuestionNumber.js, src/components/Gameboard/Rules.js, src/components/Player/Blank.js, src/components/Player/SkipRules.js, src/components/Player/StartGame.js, src/reducers/gameplay_reducer.js
=> Issue 42 skiprules

src/actions/index.js, src/components/Gameboard/CorrectAnswer.js, src/components/Gameboard/CreateGame.js, src/reducers/gameplay_reducer.js
=> Issue 48 correct answer

package-lock.json, server.js, src/actions/index.js, src/actions/socket_actions.js, src/components/Gameboard/CreateGame.js, src/components/Gameboard/Submitted.js, src/components/Player/Answer.js, src/components/screens.js, src/reducers/gameplay_reducer.js
=> Issue 45 answer questions

server.js, src/components/Gameboard/Congrats.js, src/components/Player/Answer.js, src/components/screens.js
=> Display winner and move to the roundnumber screen with play again

src/actions/index.js, src/components/Gameboard/Question.js, src/components/Gameboard/QuestionAsk.js, src/components/Gameboard/Submitted.js, src/components/Gameboard/Timer.js, src/components/Player/Answer.js, src/components/Player/Blank.js, src/components/Player/SkipRules.js
=> Issue 46 display questions

src/actions/index.js, src/components/Gameboard/AnswerPlaceBets.js, src/components/Gameboard/Timer.js, src/components/Player/PlaceBets.js
=> Issue 47 display answers

package-lock.json, package.json, server.js, src/actions/index.js, src/actions/socket_actions.js, src/components/Gameboard/AnswerPlaceBets.js, src/components/Gameboard/AnswerSeeBets.js, src/components/Gameboard/Timer.js, src/components/Player/PlaceBets.js, src/reducers/gameplay_reducer.js
resolves #59 
god bless this mess
=> Issue 59 place bets

server.js, src/components/Gameboard/AnswerSeeBets.js, src/components/Gameboard/PointsLeaderBoard.js, src/components/Gameboard/QuestionNumber.js, src/reducers/gameplay_reducer.js
=> Issue 50 endround leaderboard

src/actions/index.js
=> Remove RoomCode from database when game starts

server.js, src/actions/index.js, src/actions/socket_actions.js, src/components/Gameboard/AnswersLeaderBoard.js, src/components/Gameboard/Congrats.js, src/components/Gameboard/CorrectAnswer.js, src/components/Gameboard/CreateGame.js, src/components/Gameboard/PointsLeaderBoard.js, src/components/screens.js, src/reducers/gameplay_reducer.js
=> Issue 49 correct answer leaderboard

server.js, src/actions/index.js, src/actions/socket_actions.js, src/components/Gameboard/AnswersLeaderBoard.js, src/components/Gameboard/Congrats.js, src/components/Gameboard/CorrectAnswer.js, src/components/Gameboard/CreateGame.js, src/components/Gameboard/PointsLeaderBoard.js, src/components/Gameboard/QuestionAsk.js, src/components/Gameboard/RoomCode.js, src/components/Player/Answer.js, src/components/Player/Blank.js, src/components/Player/PlaceBets.js, src/components/Player/PlayAgain.js, src/components/Player/StartGame.js, src/components/screens.js, src/reducers/gameplay_reducer.js, src/reducers/index.js
=> Issue 52 play again

src/App.js, src/actions/index.js, src/components/Gameboard/CreateGame.js, src/components/Gameboard/options.js, src/components/index.js, src/reducers/gameplay_reducer.js, src/reducers/index.js
=> Fix game length variables

src/actions/index.js, src/reducers/index.js
- Fixed minimum number of users
- Fixed resetting question number and round number between games
- Fixed error when entering wrong room code
- TODO: send the correct user count to newly joined players
=> Fix things
